spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://10.1.99.162:5432/Lottery
    username: postgres
    password: dbuser@86136982
    testWhileIdle: true
    validationQuery: SELECT 1
    
  jpa.show-sql: true
